# NumPy — practice

Follow along with [`../lessons/07-numpy.md`](../lessons/07-numpy.md). Type the commands yourself; don't paste.


In [1]:
import numpy as np


## Creating arrays


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)
np.full(10, 5)
a=np.array([1,2,3,4,5])
np.linspace(0, 1, 5)
np.arange(0, 10, 1.5)


array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

## Multi-dimensional arrays


In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
n=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
n[1,1]

np.int64(5)

## Randomly generated arrays


In [15]:
np.random.seed(2)
myRand= 100* np.random.rand(5, 2)
myRand

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

## Element-wise operations


In [22]:
a= np.arange(5)  
a  
b= np.arange(6)
b
a+b

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

## Comparison operations


## Summarizing operations
