# Linear algebra refresher — practice

Follow along with [`../lessons/08-linear-algebra.md`](../lessons/08-linear-algebra.md). Type the commands yourself; don't paste.


In [2]:
import numpy as np


## Vector operations


In [4]:
u = np.array([1, 2, 3])
u2 = 2* u
u2

array([2, 4, 6])

In [5]:
# addition is element-wise
v = np.array([4, 5, 6])
u + v

array([5, 7, 9])

## Multiplication


In [ ]:
# dot product
uv=u*v  # this is element-wise multiplication
udotv=np.dot(u, v) # this is the dot product, "prodotto scalare" in Italian
uv==udotv
udotv

np.int64(32)

In [13]:
def vector_vector_multiplication(u, v):
    """
    Compute the dot product of two vectors u and v.
    
    Parameters:
    u (numpy.ndarray): First input vector.
    v (numpy.ndarray): Second input vector.
    
    Returns:
    float: The dot product of u and v.
    """
    assert u.shape[0] == v.shape[0], "Vectors must be of the same length"
    result = 0.0
    for i in range(u.shape[0]):
        result += u[i] * v[i]
    return result

vector_vector_multiplication(u, v)

np.float64(32.0)

In [16]:
## Matrix vector multiplication
def matrix_vector_multiplication(A, x):
    """
    Compute the product of a matrix A and a vector x.
    
    Parameters:
    A (numpy.ndarray): Input matrix of shape (m, n).
    x (numpy.ndarray): Input vector of shape (n,).
    
    Returns:
    numpy.ndarray: The resulting vector of shape (m,).
    """
    assert A.shape[1] == x.shape[0], "Number of columns in A must match number of rows in x"
    result = np.zeros(A.shape[0])
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            result[i] = vector_vector_multiplication(A[i], x)
    return result

U = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([1, 0, 1])
U.dot(x) ==matrix_vector_multiplication(U, x)

array([ True,  True,  True])

## Identity matrix


## Inverse
